name: cleanup

on:
  schedule:
    # - cron:  '1 1 * * *' # every day
    - cron:  '1 1 * * 1' # once a week
    # - cron:  '1 1 1 * *' # once a month

jobs:

  expire:
    runs-on: ubuntu-latest
    steps:

    - name: Expire Artifacts
      uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        expire-in: 1hour
