name: publish on dockerhub

on:
  # workflow_run:
  #   workflows: [ ci ]
  #   branches: [ master ]
  #   push:
  #     tags: [ 'v*' ]
  #   types:
  #     - completed
  push:
    branches: [ master ]
  release:
    types: [ published ]

env:
  image: ${{ secrets.DOCKERHUB_USERNAME }}/release-node

jobs:
  dockerhub:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Version
      uses: tcurdt/action-verify-version-npm@master

    - name: Login
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: echo -n ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build
      run: |
        echo "SHA=$GITHUB_SHA"
        docker build --build-arg SHA=$GITHUB_SHA \
          --label "SHA=$GITHUB_SHA" \
          --tag ${{ env.image }}:${GITHUB_REF##*/} \
          --tag ${{ env.image }}:latest \
          .

    - name: Push
      run: docker push ${{ env.image }}
