name: publish on npm

on:
  # workflow_run:
  #   workflows: [ ci ]
  #   branches: [ master ]
  #   push:
  #     tags: [ 'v*' ]
  #   types:
  #     - completed
  release:
    types: [ published ]

jobs:
  npm:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Version
      uses: tcurdt/action-verify-version-npm@master

    - name: Publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
        npm install
        npm publish --access=public
